In [1]:
import numpy as np

In [25]:
my_list=[1,2,3,4,5]

arr=np.array(my_list)
arr

array([1, 2, 3, 4, 5])

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr.shape # One-dimensional array

(5,)

In [5]:
# Multinested array
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arr=np.array([my_lst1,my_lst2,my_lst3])
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [6]:
arr.shape

(3, 5)

In [7]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 8, 9]])

In [8]:
## Indexing
arr[:3,:3]

array([[1, 2, 3],
       [2, 3, 4],
       [9, 7, 6]])

In [9]:
arr[1:,3:]

array([[5, 6],
       [8, 9]])

In [10]:
arr[1:,2:4]

array([[4, 5],
       [6, 8]])

In [11]:
arr[1:2,1:4]

array([[3, 4, 5]])

In [26]:
# copy of array --> array (reference type), prevent default behaviour usig copy() function
arr[3:]=100
arr

array([  1,   2,   3, 100, 100])

In [27]:
arr1=arr
arr1[3:]=200
arr1

array([  1,   2,   3, 200, 200])

In [28]:
arr

array([  1,   2,   3, 200, 200])

In [29]:
arr2=arr.copy()
arr2[3:]=300
arr2

array([  1,   2,   3, 300, 300])

In [30]:
arr

array([  1,   2,   3, 200, 200])

In [31]:
# condition checking
print(arr<2)
print(arr[arr<2])

[ True False False False False]
[1]


# In-built functions

In [32]:
arr=np.arange(1,10,step=2)
arr

array([1, 3, 5, 7, 9])

In [33]:
arr=np.linspace(0,10,25)
arr

array([ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667,
        2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ,
        4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333,
        6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667,
        8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ])

In [34]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [35]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [36]:
np.random.rand(3,3)

array([[0.0743014 , 0.67670055, 0.59539521],
       [0.39930157, 0.73745431, 0.45537523],
       [0.81290495, 0.89817908, 0.14886889]])

In [37]:
np.random.randn(3,2)

array([[-1.8414908 ,  0.91786737],
       [ 0.59488687,  0.28481127],
       [ 0.48046485,  0.18313346]])